# Generated by Django 5.2.4 on 2025-08-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desceiption',
            new_name='description',
        ),
    ]
